// NOTE: specialtyToTokenID is sacred. Do not change the values.
export const specialtyToTokenID = {
  "Allergy & Immunology": "0",
  Anesthesiology: "1",
  "Colon & Rectal Surgery": "2",
  Dermatology: "3",
  "Emergency Medicine": "4",
  "Family Medicine": "5",
  "Internal Medicine": "6",
  "Medical Genetics & Genomics": "7",
  "Neurological Surgery": "8",
  "Obstetrics & Gynecology": "9",
  Ophthalmology: "10",
  "Orthopaedic Surgery": "11",
  "Otolaryngology Head & Neck": "12",
  Pathology: "13",
  Pediatrics: "14",
  "Physical Medicine & Rehabilitation": "15",
  "Plastic Surgery": "16",
  "Preventive Medicine": "17",
  "Psychiatry & Neurology": "18",
  Radiology: "19",
  Surgery: "20",
  "Thoracic Surgery": "21",
  Urology: "22",
};

export const stateAbbreviations = {
  ALABAMA: "AL",
  ALASKA: "AK",
  "AMERICAN SAMOA": "AS",
  ARIZONA: "AZ",
  ARKANSAS: "AR",
  CALIFORNIA: "CA",
  COLORADO: "CO",
  CONNECTICUT: "CT",
  DELAWARE: "DE",
  "DISTRICT OF COLUMBIA": "DC",
  "FEDERATED STATES OF MICRONESIA": "FM",
  FLORIDA: "FL",
  GEORGIA: "GA",
  GUAM: "GU",
  HAWAII: "HI",
  IDAHO: "ID",
  ILLINOIS: "IL",
  INDIANA: "IN",
  IOWA: "IA",
  KANSAS: "KS",
  KENTUCKY: "KY",
  LOUISIANA: "LA",
  MAINE: "ME",
  "MARSHALL ISLANDS": "MH",
  MARYLAND: "MD",
  MASSACHUSETTS: "MA",
  MICHIGAN: "MI",
  MINNESOTA: "MN",
  MISSISSIPPI: "MS",
  MISSOURI: "MO",
  MONTANA: "MT",
  NEBRASKA: "NE",
  NEVADA: "NV",
  "NEW HAMPSHIRE": "NH",
  "NEW JERSEY": "NJ",
  "NEW MEXICO": "NM",
  "NEW YORK": "NY",
  "NORTH CAROLINA": "NC",
  "NORTH DAKOTA": "ND",
  "NORTHERN MARIANA ISLANDS": "MP",
  OHIO: "OH",
  OKLAHOMA: "OK",
  OREGON: "OR",
  PALAU: "PW",
  PENNSYLVANIA: "PA",
  "PUERTO RICO": "PR",
  "RHODE ISLAND": "RI",
  "SOUTH CAROLINA": "SC",
  "SOUTH DAKOTA": "SD",
  TENNESSEE: "TN",
  TEXAS: "TX",
  UTAH: "UT",
  VERMONT: "VT",
  "VIRGIN ISLANDS": "VI",
  VIRGINIA: "VA",
  WASHINGTON: "WA",
  "WEST VIRGINIA": "WV",
  WISCONSIN: "WI",
  WYOMING: "WY",
};
